# Generated by Django 5.0.6 on 2024-07-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('taskCategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='category',
            field=models.ManyToManyField(to='taskCategory.form_category'),
        ),
    ]
